### ISSUE TITLE
YML里惊喜工厂和东东工厂上车码是不同的。还有jd_sharecodes.sh没有增加惊喜工厂的语句

### ISSUE THREAD

**Issue by yellowbins** [lifeishard4me/Actions#14]
DDFACTORY_SHARECODES: ${{ secrets.DDFACTORY_SHARECODES }}
  JXFACTORY_SHARECODES: ${{ secrets.DDFACTORY_SHARECODES }}

#!/usr/bin/env bash

IFS="@"
FRUITSHARECODES_ARR=($FRUITSHARECODES)
PETSHARECODES_ARR=($PETSHARECODES)
PLANT_BEAN_SHARECODES_ARR=($PLANT_BEAN_SHARECODES)
SUPERMARKET_SHARECODES_ARR=($SUPERMARKET_SHARECODES)
DDFACTORY_SHARECODES_ARR=($DDFACTORY_SHARECODES)

**Comment by lifeishard4me** [comment]
> 
> 
> DDFACTORY_SHARECODES: ${{ secrets.DDFACTORY_SHARECODES }}
> JXFACTORY_SHARECODES: ${{ secrets.DDFACTORY_SHARECODES }}
> 
> #!/usr/bin/env bash
> 
> IFS="@"
> FRUITSHARECODES_ARR=($FRUITSHARECODES)
> PETSHARECODES_ARR=($PETSHARECODES)
> PLANT_BEAN_SHARECODES_ARR=($PLANT_BEAN_SHARECODES)
> SUPERMARKET_SHARECODES_ARR=($SUPERMARKET_SHARECODES)
> DDFACTORY_SHARECODES_ARR=($DDFACTORY_SHARECODES)

已改。
