### ISSUE TITLE
新手求助

### ISSUE THREAD

**Issue by zheng-wb** [lifeishard4me/Actions#2]
感谢分享，我是一个新手，对GitHub还不太熟悉，请问这个是fork后，加入自己的secret，就能让action跑起来吗？

**Comment by HenryTSZ** [comment]
> 感谢分享，我是一个新手，对GitHub还不太熟悉，请问这个是fork后，加入自己的secret，就能让action跑起来吗？

1. 切换到 Action 页签
2.有个让你同意的按钮, 点击
3. Github 默认 fork 的仓库 workflow 是关闭的, 需要一个一个自己手动打开
4. 打开后可以随便运行一个, 成功后就可以了

**Comment by zengxiangj** [comment]
大佬，都成你这里Frok，那你这个项目不也容易被封了啊。

**Comment by zheng-wb** [comment]
> > 感谢分享，我是一个新手，对GitHub还不太熟悉，请问这个是fork后，加入自己的secret，就能让action跑起来吗？
> 
> 1. 切换到 Action 页签
> 2. 有个让你同意的按钮, 点击
> 3. Github 默认 fork 的仓库 workflow 是关闭的, 需要一个一个自己手动打开
> 4. 打开后可以随便运行一个, 成功后就可以了

感谢回答，手动运行貌似是没问题了
请问自动运行是怎么触发的？

**Comment by HenryTSZ** [comment]
> > > 感谢分享，我是一个新手，对GitHub还不太熟悉，请问这个是fork后，加入自己的secret，就能让action跑起来吗？
> > 
> > 
> > 
> > 1. 切换到 Action 页签
> > 2. 有个让你同意的按钮, 点击
> > 3. Github 默认 fork 的仓库 workflow 是关闭的, 需要一个一个自己手动打开
> > 4. 打开后可以随便运行一个, 成功后就可以了
> 
> 感谢回答，手动运行貌似是没问题了
> 请问自动运行是怎么触发的？

那就不用管了, 到时间了会自动运行的
