### ISSUE TITLE
sos求助帖我的里面只有一个工作流没有之前所有的脚本啊

### ISSUE THREAD

**Issue by zhanghaifei1997** [lifeishard4me/Actions#3]
![image](https://user-images.githubusercontent.com/57278786/98899239-2fede880-24ea-11eb-8528-6f9bac137e0d.png)

**Comment by HenryTSZ** [comment]
@zhanghaifei1997 你 fork 错仓库了吧

**Comment by zhanghaifei1997** [comment]
没有，应该是boss把workflows里面的流程文件都删了吧，我把以前的放进去就有用了




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Henry"<notifications@github.com&gt;; 
发送时间: 2020年11月12日(星期四) 下午4:56
收件人: "lifeishard4me/Actions"<Actions@noreply.github.com&gt;; 
抄送: "亚特兰蒂斯之夜"<2428669833@qq.com&gt;; "Mention"<mention@noreply.github.com&gt;; 
主题: Re: [lifeishard4me/Actions] sos求助帖我的里面只有一个工作流没有之前所有的脚本啊 (#3)





 
@zhanghaifei1997 你 fork 错仓库了吧

**Comment by HenryTSZ** [comment]
这个仓库就没有 sync-lxk0301-scripts 这个 workflow 啊

**Comment by zhanghaifei1997** [comment]
所以可以用这这个Action里面的workflow




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Henry"<notifications@github.com&gt;; 
发送时间: 2020年11月12日(星期四) 下午5:16
收件人: "lifeishard4me/Actions"<Actions@noreply.github.com&gt;; 
抄送: "亚特兰蒂斯之夜"<2428669833@qq.com&gt;; "Mention"<mention@noreply.github.com&gt;; 
主题: Re: [lifeishard4me/Actions] sos求助帖我的里面只有一个工作流没有之前所有的脚本啊 (#3)





 
这个仓库就没有 sync-lxk0301-scripts 这个 workflow 啊
 
&mdash;

**Comment by gee1k** [comment]
缺少星推官
