### ISSUE TITLE
请问 这个互助码的使用方式规则在哪里呢？

### ISSUE THREAD

**Issue by Kirietoan** [lifeishard4me/Actions#39]
我看我这个助力码上车里面没有东西 是自动获取助力码的吗？
谢谢！

**Comment by jackpater** [comment]
我也不太清楚，我昨天是本地运行，程序有提示自己的xx互助码
![image](https://user-images.githubusercontent.com/24645106/103084989-6192bd00-461b-11eb-968e-e396a5f34490.png)
