### ISSUE TITLE
jd_pigPet 每天运行失败

### ISSUE THREAD

**Issue by likaiyong** [lifeishard4me/Actions#5]
![image](https://user-images.githubusercontent.com/29756473/99333613-7e6cff80-28bb-11eb-9035-952e40110ef5.png)

**Comment by zzan1** [comment]
同样的问题~

`2s
Run git clone https://gitee.com/lxk0301/jd_scripts.git ~/scripts
  git clone https://gitee.com/lxk0301/jd_scripts.git ~/scripts
  shell: /bin/bash -e {0}
Cloning into '/home/runner/scripts'...
error: RPC failed; HTTP 403 curl 22 The requested URL returned error: 403
fatal: error reading section header 'shallow-info'
Error: Process completed with exit code 128.`
