### ISSUE TITLE
cookie失效，更新后依然提示

### ISSUE THREAD

**Issue by kerncoola** [lifeishard4me/Actions#8]
共175个京东账号

京小超已改版,目前暂不用助力, 故无助力码

开始【京东账号1】null

==============📣系统通知📣==============
京小超
【提示】cookie已失效
京东账号1 null
请重新登录获取
https://bean.m.jd.com/

**Comment by webfamer** [comment]
然后server酱就推送了n个通知，我还以为咋了

**Comment by kerncoola** [comment]
我也是，重新update了一下cookie就稳了

**Comment by webfamer** [comment]
修复了，能用了
![image](https://user-images.githubusercontent.com/38120239/99638103-bc675080-2a80-11eb-8382-e8ebf694a526.png)

**Comment by kerncoola** [comment]
稳了
